version: "3.9"

services:
    streamlit:
        build: .
        hostname: "streamlit"
        container_name: "streamlit"
        ports:
            - "8501:8501"
        volumes:
            - .:/main
