version: '3.4'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ass
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_URL: 'http://localhost:9000'
    networks:
      - app_network
    volumes:
      - .:/var/www/html

  db:
    image: postgres
    environment:
      POSTGRES_DB: ass
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db_network

volumes:
    postgres-data:

networks:
  app_network:
  db_network:
