version: '1.1'

services:
    ass:
        build: .
        hostname: "ass"
        container_name: "ass"
        ports:
            - "8889:8889"
            - "5173:5173"
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: ass_db
            DB_PORT: 5432
            DB_DATABASE: ass
            DB_USERNAME: root
            DB_PASSWORD: root
            APP_URL: '0.0.0.0:8889'
            DUSK_DRIVER: remote
            DUSK_REMOTE_URL: "http://selenium:4444/wd/hub"
        networks:
            network:
                aliases:
                    - ass
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - selenium
#        command: sh -c "php artisan serve --host=0.0.0.0 --port=8889 & npm run dev"
        command: sh -c "php artisan serve --host=0.0.0.0 --port=8889"

    selenium:
        image: selenium/standalone-chrome:4.3.0-20220706
        hostname: "selenium"
        container_name: "selenium"
        ports:
            - "4444:4444"
        networks:
            network:
                aliases:
                    - selenium

    db:
        image: postgres
        hostname: "ass_db"
        container_name: "ass_db"
        ports:
            - "5432:54342"
        environment:
            - POSTGRES_DB=ass
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - PGDATA=/var/lib/postgresql/data/ass/
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - network

volumes:
    postgres-data:

networks:
    network:


