version: '3.4'

services:
    ass:
        build: .
        hostname: "ass"
        container_name: "ass"
        ports:
            - "8889:8889"
            - "5173:5173"
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: ass_db
            DB_PORT: 5432
            DB_DATABASE: ass
            DB_USERNAME: root
            DB_PASSWORD: root
            APP_URL: '0.0.0.0:8889'
            DUSK_DRIVER: chrome
#            DUSK_DRIVER: remote
#            DUSK_REMOTE_URL: "http://0.0.0.0:4444/wd/hub"
        networks:
            - network
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - selenium
        command: sh -c "php artisan serve --host=0.0.0.0 --port=8889 & npm run dev"

    selenium:
        image: selenium/standalone-chrome
        hostname: "selenium"
        container_name: "selenium"
        ports:
            - "4444:4444"
#        links:
#            - ass:selenium
        networks:
            network:
                aliases:
                  - selenium

#    chrome:
#        image: selenium/node-chrome:4.8.3-20230404
#        shm_size: 2gb
#        depends_on:
#            - selenium-hub
#        environment:
#            - SE_EVENT_BUS_HOST=selenium-hub
#            - SE_EVENT_BUS_PUBLISH_PORT=4442
#            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#        ports:
#            - "6900:5900"
#
#    edge:
#        image: selenium/node-edge:4.8.3-20230404
#        shm_size: 2gb
#        depends_on:
#            - selenium-hub
#        environment:
#            - SE_EVENT_BUS_HOST=selenium-hub
#            - SE_EVENT_BUS_PUBLISH_PORT=4442
#            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#        ports:
#            - "6901:5900"
#
#    firefox:
#        image: selenium/node-firefox:4.8.3-20230404
#        shm_size: 2gb
#        depends_on:
#            - selenium-hub
#        environment:
#            - SE_EVENT_BUS_HOST=selenium-hub
#            - SE_EVENT_BUS_PUBLISH_PORT=4442
#            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#        ports:
#            - "6902:5900"
#
#    selenium-hub:
#        image: selenium/hub:4.8.3-20230404
#        ports:
#            - "4442:4442"
#            - "4443:4443"
#            - "4444:4444"

    db:
        image: postgres
        hostname: "ass_db"
        container_name: "ass_db"
        ports:
            - "5432:54342"
        environment:
            - POSTGRES_DB=ass
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - PGDATA=/var/lib/postgresql/data/ass/
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - network

volumes:
    postgres-data:

networks:
    network:


