version: '3.4'

services:
  app:
    build: ./docker
    ports:
      - "9000:9000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ass
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - app_network
    volumes:
      - .:/var/www/html

  db:
    image: postgres
    environment:
      POSTGRES_DB: ass
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - db_network

networks:
  app_network:
  db_network:
